### PR TITLE
Refactor code to use plugin instead of preference

### PR DESCRIPTION
**Pull request by sinisa-colic**
Using preference can create compatibility issues with original class because of changes made to constructor arguments made by Magento core team. Just in the last year they added 5 new arguments which can be seen here: [AccountManagement model blame](https://github.com/magento/magento2/blame/2.3-develop/app/code/Magento/Customer/Model/AccountManagement.php)

### CODE REVIEW

**Comment by tdgroot** [comment]
Hi @seeney97,

Thank you for your proposal! I was actually surprised that people are interested in this module. 

I totally agree with you and your suggested changes make sense. There need to be done one extra change though. 

Could you add a plugin for resetting a password as well? On a traditional Magento frontend, those are the two main points password validation kicks in.

**Review by tdgroot — CHANGES_REQUESTED** [review]
Please add a plugin for resetting a password as well!

**Comment by tdgroot** [comment]
@seeney97 thanks for getting back to it so quickly! I will test the changes coming week and get it merged :).

**Comment by sinisa-colic** [comment]
You are welcome 😄. I came up with idea to make exactly the same module, but after finding out it was already created i decided to improve it instead.

**Comment by tdgroot** [comment]
@sinisa-colic sorry for getting back to this PR so late. I merged your changes, thanks again!

**Pull request merged**
